### ISSUE TITLE
Exception output shown in terminal when reaching last page (version 0.3)

### ISSUE THREAD

**Issue by hartwork** [Schnouki/pympress#18]
```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/pympress/document.py", line 338, in navigation_cb
    self.next()
  File "/usr/lib64/python2.7/site-packages/pympress/document.py", line 315, in next
    self.goto(self.nb_current + 1)
  File "/usr/lib64/python2.7/site-packages/pympress/document.py", line 311, in goto
    self.presenter.set_page(current, next, page)
  File "/usr/lib64/python2.7/site-packages/pympress/presenter.py", line 326, in set_page
    self.page_next.render_on(self.da_next)
AttributeError: 'NoneType' object has no attribute 'render_on'
```

**Comment by Schnouki** [comment]
Hi, this repo is no longer maintained. Please have a look at https://github.com/Cimbali/pympress instead.
